name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: simple_auth
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: |
          frontend/package-lock.json
          backend/package-lock.json
    
    - name: Install backend dependencies
      run: npm ci
      working-directory: ./backend
    
    - name: Build backend
      run: npm run build
      working-directory: ./backend
    
    - name: Start backend server
      run: |
        npm run start:prod &
        echo $! > backend.pid
        # Wait for backend to be ready
        echo "Waiting for backend to start..."
        timeout 60 bash -c 'until curl -f http://localhost:3001/api/health 2>/dev/null || curl -f http://localhost:3001/api 2>/dev/null; do echo "Waiting..."; sleep 3; done'
        echo "Backend is ready!"
      working-directory: ./backend
      env:
        NODE_ENV: production
        PORT: 3001
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USERNAME: postgres
        DB_PASSWORD: password
        DB_NAME: simple_auth
        JWT_SECRET: test-jwt-secret-for-ci
        JWT_REFRESH_SECRET: test-refresh-secret-for-ci
        FRONTEND_URL: http://localhost:3000
    
    - name: Install frontend dependencies
      run: npm ci
      working-directory: ./frontend

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
      working-directory: ./frontend

    - name: Start frontend server
      run: |
        npm run build
        npm run start &
        echo $! > frontend.pid
        # Wait for frontend to be ready
        echo "Waiting for frontend to start..."
        timeout 60 bash -c 'until curl -f http://localhost:3000 2>/dev/null; do echo "Waiting..."; sleep 3; done'
        echo "Frontend is ready!"
      working-directory: ./frontend
      env:
        NEXT_PUBLIC_API_URL: http://localhost:3001/api

    - name: Run Playwright tests
      run: npm run test:e2e -- --project=chromium
      working-directory: ./frontend
      timeout-minutes: 30
      env:
        CI: true
        NEXT_PUBLIC_API_URL: http://localhost:3001/api
    
    - name: Stop servers
      if: always()
      run: |
        echo "Stopping frontend server..."
        if [ -f frontend/frontend.pid ]; then
          # Kill the frontend process tree
          FRONTEND_PID=$(cat frontend/frontend.pid)
          echo "Killing frontend process tree starting from PID: $FRONTEND_PID"
          pkill -P $FRONTEND_PID || true
          kill $FRONTEND_PID || true
          rm frontend/frontend.pid
        fi
        
        echo "Stopping backend server..."
        if [ -f backend/backend.pid ]; then
          # Kill the backend process tree
          BACKEND_PID=$(cat backend/backend.pid)
          echo "Killing backend process tree starting from PID: $BACKEND_PID"
          pkill -P $BACKEND_PID || true
          kill $BACKEND_PID || true
          rm backend/backend.pid
        fi
        
        # Additional cleanup - kill any remaining Node.js processes
        echo "Cleaning up any remaining Node.js processes..."
        pkill -f "node.*start:prod" || true
        pkill -f "next start" || true
        
        # Wait a moment for processes to terminate
        sleep 2
        
        echo "Server cleanup completed."
    
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: frontend/test-results/
        retention-days: 7